### ISSUE TITLE
can't find executable

### ISSUE THREAD

**Issue by rhaynes74** [ttscoff/hookapp#1]
Hi folks, I am a new user of the hookapp - I purchased the hookapp pro today.  I then did the following (since I am a terminal user):

sudo gem install hookapp                                                                 
Password:
Successfully installed hookapp-2.0.3
invalid options: -ri
(invalid options are ignored)
Parsing documentation for hookapp-2.0.3
Done installing documentation for hookapp after 0 seconds
1 gem installed

╭
╰─ hook                                                                                     
zsh: command not found: hook

So the install doesn't really seem successful - I started a new zsh session but no dice. 

Best,
RH

**Comment by ttscoff** [comment]
Sorry for the delayed reply, I missed the notification about this. It may
have to do with your ruby setup, but the gem executable should have been
installed to `/usr/local/bin` and should be available no matter what. Can
you run `ls /usr/local/bin/hook` and let me know if it finds a file?

**Comment by rhaynes74** [comment]
Thanks for the reply, it was indeed a gem problem.  I had borked my .zshrc sometime ago and forgot to add the path back for the binaries.    Enjoying the cli tool!

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.
