### ISSUE TITLE
execution error: The variable bookmark is not defined.

### ISSUE THREAD

**Issue by Tokubara** [ttscoff/hookapp#8]
This is the first command I executed since I installed hookapp.
```
hook clip  /Users/quebec/Downloads/logins.csv
```
The error message is:
```
60:68: execution error: The variable bookmark is not defined. (-2753)
error: Error getting bookmark for /Users/quebec/Downloads/logins.csv
```

**Comment by Tokubara** [comment]
Yes, every file path just gives the same result.
```
$ gem --version      
3.0.3
$ ruby --version                    
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
```
My os version is 10.15.7(Catalina).

**Comment by Tokubara** [comment]
Other commands do not work, too.
```
$ hook find asc
90:98: syntax error: Expected class name but found identifier. (-2741)
90:98: syntax error: Expected class name but found identifier. (-2741)
No bookmarks
```
But I do have a hook with "asc" in name.

**Comment by Tokubara** [comment]
I suspect it's due to that Hook changes its name to HookMark, so macos cannot find the application?

**Comment by Tokubara** [comment]
It asks me: What is Hook? So I still think it is dut to the name of the application.
<img width="680" alt="image" src="https://user-images.githubusercontent.com/32409331/201131600-d4013280-67d9-4604-88b6-60626eae7854.png">

**Comment by ttscoff** [comment]
Interesting. I'm running the latest Hookmark and if I change Hook to Hookmark, script editor changes it right back. And all of the commands execute properly for me. I'll have to look into why that is.

**Comment by ttscoff** [comment]
I just pushed v1.2.0 with all references to Hook updated to Hookmark. Seems to work fine on my machine, please use `gem upgrade hookapp` and let me know if it works for you.

**Comment by Tokubara** [comment]
Thank you, it works!
